[package]
name = "argparse-example"
version = "0.1.0"
authors = ["Christian Empting <Christian.Empting@zuehlke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
